### ISSUE TITLE
Fix url to CLR data in the Google Sheet

### ISSUE THREAD

**Issue by jmonlong** [human-pangenomics/HG002_Data_Freeze_v1.0#1]
It looks like the url to the CLR data from PacBio is broken in https://docs.google.com/spreadsheets/d/1eUXfyTqWVy9O3bYYyZdiEoWhnztUJXIf7u8X3UE-ryg/edit?usp=sharing

It's points to `https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=HG002/hpp_HG002_NA24385_son_v1/PacBio_CLR/PB_SV-HG002-CLR/` but I think it should be `https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=HG002/hpp_HG002_NA24385_son_v1/PacBio_CLR/PB_HG002-CLR-SvDetection/`

**Comment by mitenjain** [comment]
Done. Thank you @jmonlong :)
